### ISSUE TITLE
Arbitrary nested data

### ISSUE THREAD

**Issue by ewjoachim** [dropseed/combine#76]
Hello, and thanks for the project,

I'm wondering if there's a way to add nested data in the Jinja context: if I try to put nested data in `combine.yml` variables (such as a dict), the variable is not injected in the context anymore.

What I'm trying to achieve is build a 4 page static website (1 main page + 1 page for terms & conditions, both with translations in 2 languages), and I want as much as possible of the data to not be hardcoded in the repo of the code, so I'll probably have a Python script read the data from the source and write a yml file somewhere before running combine. Nesting data in this case is needed to ensure that I have the same structure in the 2 languages, and avoid having to redefine my template twice with just different variable names, but if you think there's a better way to achieve this, I'll take it :)

Thanks !

**Comment by davegaeddert** [comment]
Thanks for pointing it out! I think it will probably work if you put it under the `default` key, like this:
```yaml
variables:
  test:
    default:
      key: val
      key2: val2
```

That's an interesting quirk of how it's designed though...

For what it's worth, I have also been thinking that a `from_file` would be a nice feature (sort of like `from_env`) that would know how to load a YAML, JSON, etc. based on the filename. So you could potentially do something like this including your script:
```yaml
# combine.yml
steps:
- run: python generate_data.py

variables:
  data:
    from_file: data.json
```

Let me know if the `default` key does it for you. I'd be open to pursuing `from_file` if that helps (or merging a PR if that's something you want to contribute).
